=== Sailorhz/RecipeBox---DatapipeLine/RecipeBoxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- Defines a complex type named "RecipeType".Indicates that 4 elements defined within it  -->
  <xs:complexType name="RecipeType">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID"/>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Price" type="xs:decimal"/>
      <!-- Defines an element named "Description". -->
      <xs:element name="Description">
        <!-- Specifies application-specific information about the element. -->
          <xs:annotation>
            <xs:appinfo>Description</xs:appinfo>
            <!-- Provides human-readable documentation about the element. -->
            <xs:documentation>Description</xs:documentation>
          </xs:annotation>
      </xs:element>
      <!-- Defines an element named "Ingredient" which can occur one or more times (minOccurs="1" maxOccurs="unbounded") -->
      <xs:element name="Ingredient" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="VeganCategory">
        <!-- Defines a simple type (enumeration) for the "VeganCategory" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="None"/>
            <xs:enumeration value="Vegetarian"/>
            <xs:enumeration value="Vegan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <!-- Defines an element named "HealthCategory"  -->
      <xs:element name="HealthCategory">
        <!-- Defines a simple type (enumeration) for the "HealthCategory" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="LowFat"/>
            <xs:enumeration value="LowCarb"/>
            <xs:enumeration value="None"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <!-- Defines an element named "Review" which can occur zero or more times, each containing data of type "ReviewType" representing reviews of the recipe. -->
      <xs:element name="Review" type="ReviewType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
<!-- Defines a complex type named "ReviewType". having <rating> 1to 5 with it and also having text review with it.  -->
  <xs:complexType name="ReviewType">
    <xs:sequence>
      <xs:element name="CustomerEmail" type="xs:string"/>
      <xs:element name="Rating">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Text">
        <xs:annotation>
            <xs:appinfo>Text</xs:appinfo>
            <xs:documentation>Text</xs:documentation>
          </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<!-- Defines a complex type named "CustomerType". -->
  <xs:complexType name="CustomerType">
    <xs:sequence>
      <!-- Defines an element named "Name" of type xs:string, representing the name of the customer. -->
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Gender">
        <!-- Defines a simple type (enumeration) for the "Gender" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Male"/>
            <xs:enumeration value="Female"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Birthday" type="xs:date"/>
      <xs:element name="Email">
         <!-- Defines a simple type (restriction) for the "Email" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Specifies a regular expression pattern that matches email addresses. -->
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PhoneNo" type="xs:string"/>
      <xs:element name="Address" type="xs:string"/>
      <xs:element name="Order" type="OrderType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

<!-- Defines a complex type named "OrderType". -->
  <xs:complexType name="OrderType">
    <xs:sequence>
      <!-- Defines an element named "Content" of type "ContentType". It can occur one or more times (minOccurs="1" and maxOccurs="unbounded"). -->
      <xs:element name="Content" type="ContentType" minOccurs="1" maxOccurs="unbounded"/>   
      <xs:element name="Delivery" type="DeliveryType"/>
    </xs:sequence>
  </xs:complexType>
<!-- Defines a complex type named "DeliveryType". -->
  <xs:complexType name="DeliveryType">
    <xs:sequence>
      <xs:element name="DeliveryDate" type="xs:date"/>
      <xs:element name="DeliveryService">
        <!-- Specifies a simple type (enumeration) for the "DeliveryService" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Delivery Co."/>
            <xs:enumeration value="Delivery Express"/>
            <xs:enumeration value="Collection Point"/>
          </xs:restriction>
        </xs:simpleType>
       </xs:element>
      <xs:element name="Status">
        <!-- Specifies a simple type (enumeration) for the "Status" element. -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ordered"/>
            <xs:enumeration value="Prepared"/>
            <xs:enumeration value="Departed"/>
            <xs:enumeration value="Received"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<!-- Declares a complex type named "ContentType". -->
  <xs:complexType name="ContentType">
    <xs:sequence>
      <xs:element name="RecipeId" type="xs:string"/>
      <xs:element name="Quantity" type="xs:positiveInteger"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Root -->
  <xs:element name="RecipeBox">

    <xs:complexType>
      <xs:sequence>
        <!-- Defines an element named "Customer" with a type of "CustomerType". It can occur zero or more times within "RecipeBox". same as "RecipeType" -->
        <xs:element name="Customer" type="CustomerType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="Recipe" type="RecipeType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence> 
    </xs:complexType>

    <!-- Key is defined here (using Id) to enforce uniqueness -->
      <xs:key name="RecipeKey">
        <xs:selector xpath="RecipeBox/Recipe"/>
        <xs:field xpath="Id"/>
      </xs:key>
      <!-- A keyref is defined to link RecipeId in Order/Content to Id in Recipe -->
      <xs:keyref name="RecipeRef" refer="RecipeKey">
        <xs:selector xpath="RecipeBox/Customer/Order/Content"/>
        <xs:field xpath="RecipeId"/>
      </xs:keyref>
      <!-- Key is defined here (using Email) to enforce uniqueness -->
      <xs:key name="CustomerEmailKey">
        <xs:selector xpath="RecipeBox/Customer"/>
        <xs:field xpath="Email"/>
      </xs:key>
      <!-- A keyref is defined to link CustomerEmail in ReviewType to Email in CustomerType -->
      <xs:keyref name="CustomerEmailRef" refer="CustomerEmailKey">
        <xs:selector xpath="RecipeBox/Recipe/Reviews"/>
        <xs:field xpath="CustomerEmail"/>
      </xs:keyref>
  </xs:element>
 
 </xs:schema>

=== Sailorhz/RecipeBox---DatapipeLine/RecipeBoxDataSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the root element of the XML document, named "RecipeBox". This attribute specifies the location of the XML Schema Definition (XSD) file that defines the structure and constraints for the "RecipeBox" document. In this case, it points to the RecipeBoxSchema.xsd file. -->
<RecipeBox xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RecipeBoxSchema.xsd">
   <!-- This snippet provides details about a single customer within the "RecipeBox" document. -->
   <!-- This tag indicates the beginning of a "Customer" element. -->
    <Customer> 
        <Name>Tom Hiddleston</Name>
        <Gender>Male</Gender>
        <Birthday>1981-02-09</Birthday>
        <Email>Tom.Hiddleston@example.com</Email>
        <PhoneNo>123-456-7890</PhoneNo>
        <Address>123 Main St, West End, London</Address>
        <!-- This tag indicates the beginning of an "Order" element. A customer can have multiple orders. -->
        <Order>
            <!-- indicates the beginning of a "Content" element within the order. Each "Content" element represents a specific recipe and its quantity in the order. -->
            <Content>
                <!-- specifies the ID of the recipe included in the order. -->
                <RecipeId>R1</RecipeId>
                <!-- specifies the quantity of the recipe included in the order. -->
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R2</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <!-- indicates the beginning of a "Delivery" element within the order. It provides details about the delivery of the order. -->
            <Delivery>
                <!-- the delivery date of the order, which is March 9th, 2024. -->
                <DeliveryDate>2024-03-09</DeliveryDate>
                <!-- specifies the delivery service used for the order. -->
                <DeliveryService>Delivery Express</DeliveryService>
                <!-- specifies the status of the delivery, which is "Received". -->
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R1</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R2</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-11</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R3</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-15</DeliveryDate>
                <DeliveryService>Delivery Express</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Rebecca Ferguson</Name>
        <Gender>Female</Gender>
        <Birthday>1983-10-19</Birthday>
        <Email>rf@example.com</Email>
        <PhoneNo>987-654-3210</PhoneNo>
        <Address>456 Oak St, Stockholm</Address>
        <Order>
            <Content>
                <RecipeId>R1</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-10</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R8</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-12</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R1</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Content>
                <RecipeId>R8</RecipeId>
                <Quantity>6</Quantity>
            </Content>
            <Content>
                <RecipeId>R3</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-18</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Ordered</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Sam wills</Name>
        <Gender>Male</Gender>
        <Birthday>1990-01-01</Birthday>
        <Email>samw@example.com</Email>
        <PhoneNo>234-456-7890</PhoneNo>
        <Address>123 Main St, Anytown, USA</Address>
        <Order>
            <Content>
                <RecipeId>R1</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R3</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-09</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Linda Pitt</Name>
        <Gender>Female</Gender>
        <Birthday>1983-05-15</Birthday>
        <Email>linda.pitt@example.com</Email>
        <PhoneNo>988-654-3210</PhoneNo>
        <Address>50 Hackney St, Othertown, USA</Address>
        <Order>
            <Content>
                <RecipeId>R3</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-10</DeliveryDate>
                <DeliveryService>Delivery Express</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R4</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R5</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-11</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Alice Johnson</Name>
        <Gender>Female</Gender>
        <Birthday>1995-08-20</Birthday>
        <Email>alice.johnson@example.com</Email>
        <PhoneNo>111-222-3333</PhoneNo>
        <Address>789 Elm St, Another Town, USA</Address>
        <Order>
            <Content>
                <RecipeId>R4</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R5</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-11</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
        <Order>
            <Content>
                <RecipeId>R7</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R10</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R9</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-17</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Bob Miller</Name>
        <Gender>Male</Gender>
        <Birthday>1980-12-10</Birthday>
        <Email>bob.miller@example.com</Email>
        <PhoneNo>444-555-6666</PhoneNo>
        <Address>321 Maple Ave, Cityville, USA</Address>
        <Order>
            <Content>
                <RecipeId>R6</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-12</DeliveryDate>
                <DeliveryService>Delivery Express</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Emily Brown</Name>
        <Gender>Female</Gender>
        <Birthday>1992-04-15</Birthday>
        <Email>emily.brown@example.com</Email>
        <PhoneNo>999-888-7777</PhoneNo>
        <Address>456 Pine St, Smalltown, USA</Address>
        <Order>
            <Content>
                <RecipeId>R7</RecipeId>
                <Quantity>2</Quantity>
            </Content>
            <Content>
                <RecipeId>R8</RecipeId>
                <Quantity>1</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-13</DeliveryDate>
                <DeliveryService>Delivery Express</DeliveryService>
                <Status>Received</Status>
            </Delivery>
        </Order>
    </Customer>

    <Customer>
        <Name>Michael Davis</Name>
        <Gender>Male</Gender>
        <Birthday>1995-11-22</Birthday>
        <Email>michael.davis@example.com</Email>
        <PhoneNo>333-444-5555</PhoneNo>
        <Address>789 Oak St, Countryside, USA</Address>
        <Order>
            <Content>
                <RecipeId>R8</RecipeId>
                <Quantity>3</Quantity>
            </Content>
            <Delivery>
                <DeliveryDate>2024-03-14</DeliveryDate>
                <DeliveryService>Delivery Co.</DeliveryService>
                <Status>Received</Status>
